---
- name: "{{ job }}"
  vars_files:
    - /vars/defaults.yaml
  roles:
    - role: registry
      when: "{{ job }}" == "install_registry"
    - role: populate
      when: "{{ job }}" == "populate_images"
    - role: deploy
      when: "{{ job }}" == "deploy_applications"