---

- name: "Make sure pre-requisites are satisfied"
  hosts: localhost
  become: yes
  roles:
    - pre

- name: "Install"
  hosts: localhost
  become: yes
  vars_files:
    - defaults.yaml
  roles:
    - deploy_registry
    - populate_registry
    - deploy_applications
