---

- name: Ensure aptitude is available
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Ensure system packages are available
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https',
          'ca-certificates',
          'curl',
          'software-properties-common',
          'python3-pip',
          'virtualenv',
          'python3-setuptools']

- name: Ensure Docker GPG Key is available
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ensure Docker Repository is available
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Ensure Docker is available
  apt: update_cache=yes name=docker-ce state=latest

- name: Ensure Docker Module for Python is available
  pip:
    name: docker