---

- name: Pull Image
  block:
    - name: Try pulling from the local registry
      docker_image:
        name: "{{ item }}"
        state: present

  rescue:
    - name: Pull from docker hub
      docker_image:
        name: "{{ item }}"
        state: present
  loop: [
    'registry:2.7.1'
  ]

- name: Deploy Registry
  block:
    - name: Try using a local image
      docker_container:
        detach: yes
        image: "{{ item.image }}"
        name: "{{ item.name }}"
        published_ports: [ "{{ item.port_mapping }}" ]
        restart_policy: always
      loop:
        - { image: 'localhost:5000/registry:2.7.1', name: 'registry', port_mapping: '5000:5000' }
  rescue:
    - name: Use the docker hub image
      docker_container:
        detach: yes
        image: "{{ item.image }}"
        name: "{{ item.name }}"
        published_ports: [ "{{ item.port_mapping }}" ]
        restart_policy: always
      loop:
        - { image: 'registry:2.7.1', name: 'registry', port_mapping: '5000:5000' }